affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 10
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 1
symbolic.funs_name.0:
- - tanh
  - sin
  - cos
  - 1/x
  - sin
symbolic_enabled: true
width:
- - 5
  - 0
- - 1
  - 0
