affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 5
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 1
symbolic.funs_name.0:
- - x^4
  - 1/x^2
  - tanh
  - sqrt
  - x^4
  - exp
  - x^3
  - x^4
  - sin
  - x^4
  - exp
  - x^4
  - exp
  - x^3
  - sin
  - exp
symbolic_enabled: true
width:
- - 16
  - 0
- - 1
  - 0
