affine_trainable: false
auto_save: false
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 3
grid_eps: 0.02
grid_range: !!python/tuple
- 0.1
- 0.9
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 0
symbolic.funs_name.0:
- - 1/x^2
  - 1/x^2
  - cos
  - 1/x^2
  - 1/x^2
  - exp
  - 1/x^2
  - 1/x^2
  - 1/x^2
  - cos
  - 1/x^2
  - 1/x^2
  - 1/x^2
  - 1/x^2
  - 1/x^2
  - 1/x^2
  - 1/x^2
  - 1/x^2
  - 1/x^2
  - cos
  - 1/x^2
  - x^2
  - 1/x^2
  - 1/x^2
  - 1/x^2
  - 1/x^2
  - sin
  - cos
  - cos
  - x^4
symbolic_enabled: true
width:
- - 30
  - 0
- - 1
  - 0
