affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 5
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 0
round: 0
sb_trainable: true
sp_trainable: true
state_id: 2
symbolic.funs_name.0:
- - exp
  - x
  - x
  - x
- - exp
  - x
  - x
  - exp
- - exp
  - x
  - x
  - sin
- - '0'
  - '0'
  - x
  - x
symbolic.funs_name.1:
- - x
  - x
  - x
  - cos
symbolic_enabled: true
width:
- - 4
  - 0
- - 4
  - 0
- - 1
  - 0
