affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 5
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 0
round: 0
sb_trainable: true
sp_trainable: true
state_id: 2
symbolic.funs_name.0:
- - sin
  - sin
  - tanh
  - x^2
- - sin
  - tanh
  - tanh
  - x^2
- - sin
  - 1/x^2
  - tanh
  - exp
- - sin
  - cos
  - tanh
  - x^4
symbolic.funs_name.1:
- - sin
  - tanh
  - tanh
  - cos
symbolic_enabled: true
width:
- - 4
  - 0
- - 4
  - 0
- - 1
  - 0
